### ISSUE TITLE
1-D Array Error

### ISSUE THREAD

**Issue by ndharms** [ReactionMechanismGenerator/AutoTST#13]
Occasionally when running conformational analysis, the following error is returned:

```
Traceback (most recent call last):
  File "transitionstates.py", line 36, in <module>
    rxn.generate_conformers(calculator=Hotbit())
  File "/home/harms.n/Code/AutoTST/autotst/reaction.py", line 510, in generate_conformers
    conformers = systematic_search(conformer, delta=60)
  File "/home/harms.n/Code/AutoTST/autotst/conformer/systematic.py", line 271, in systematic_search
    is_close = (np.sqrt(((df.distances[index] - df.distances)**2).apply(np.mean)) > 0.1)
  File "/home/harms.n/anaconda2/envs/rmg_env/lib/python2.7/site-packages/pandas/core/ops.py", line 745, in wrapper
    dtype=dtype,
  File "/home/harms.n/anaconda2/envs/rmg_env/lib/python2.7/site-packages/pandas/core/ops.py", line 653, in _construct_result
    return left._constructor(result, index=index, name=name, dtype=dtype)
  File "/home/harms.n/anaconda2/envs/rmg_env/lib/python2.7/site-packages/pandas/core/series.py", line 264, in __init__
    raise_cast_failure=True)
  File "/home/harms.n/anaconda2/envs/rmg_env/lib/python2.7/site-packages/pandas/core/series.py", line 3275, in _sanitize_array
    raise Exception('Data must be 1-dimensional')
Exception: Data must be 1-dimensional
```

This occurs after AutoTST has generated an ensemble of conformers, but is having an issue when identifying unique low energy conformers. Probably going to run through conformers one at a time rather than using Pandas logic to identify unique conformers.

**Comment by ndharms** [comment]
Solved by doing a "dumber" way of identifying unique conformers
